### ISSUE TITLE
make sure loops crossfade

### ISSUE THREAD

**Issue by wolftune** [brarcher/baby-sleep-sounds#17]
I didn't actually thoroughly check, but I found a case with at least a previous version of this where the loop point had a tiny break in the sound. Ideally, the loops should crossfade or be absolutely seamless.

**Comment by brarcher** [comment]
I think you are right. The Android API I was using to loop the audio did not provide a seamless loop, and instead had a brief break.

I've added some changes which should resolve this. Instead of playing ~1 minute of audio in a loop and hoping it works, the files are reduced to about ~10 seconds in length and cross-fade from the end of one loop into the next. With this, at least on my phone, it is hard to tell where the restart is.

**Comment by brarcher** [comment]
This should now be resolved. Look for this change in the next release. If you have any feedback, please let me know. (:

**Comment by wolftune** [comment]
Yay, thanks! I'll see how it is once the update is on F-droid. I'll trust your judgment here, although I generally would have aimed for longer 1-minute recordings *if* the longer recording itself was varied and not just a recording of a loop (just because I don't like *noticing* that something is a clear short loop). In the end, the only thing that matters is that it's good for sleeping babies, of course. Cheers
